from utils.normalizar_cnpj import normalizar_cnpj_areal
from utils.regex import buscar_regex
from utils.identificar_modelo_layout import identificar_layout
from utils.construtor_extracao import extrair_dados
from utils.cabecalho_tabela import cabecalho_tabela
